"""HTML compliance report generator with RED/Orange/Green visual summary."""
from __future__ import annotations

import html
import json
from datetime import datetime, timezone
from pathlib import Path


def _severity_color(severity: str) -> str:
    return {
        "critical": "#c0392b",
        "high": "#e67e22",
        "medium": "#f39c12",
        "low": "#27ae60",
        "informational": "#2980b9",
    }.get(severity.lower(), "#7f8c8d")


def _status_badge(compliant: bool) -> str:
    if compliant:
        return '<span style="color:#27ae60;font-weight:bold;">PASS</span>'
    return '<span style="color:#c0392b;font-weight:bold;">FAIL</span>'


class HTMLReportGenerator:
    def __init__(self, reports_dir: str) -> None:
        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        instance_id: str,
        job_id: str,
        eval_results: list[dict],
        instance_name: str = "",
        system_info: dict | None = None,
    ) -> str:
        """Return file path to generated HTML report."""
        total = len(eval_results)
        pass_count = sum(1 for r in eval_results if r.get("compliant"))
        fail_count = total - pass_count
        pass_pct = round(pass_count / total * 100, 1) if total else 0.0
        color = "#27ae60" if pass_pct >= 80 else ("#e67e22" if pass_pct >= 50 else "#c0392b")

        rows = ""
        for r in eval_results:
            sev_html = f'<span style="color:{_severity_color(r.get("severity","medium"))}">{html.escape(r.get("severity","medium").upper())}</span>'
            rows += f"""<tr>
              <td>{html.escape(r.get("rule_id",""))}</td>
              <td>{html.escape(r.get("title",""))}</td>
              <td>{sev_html}</td>
              <td>{html.escape(r.get("component_type",""))}</td>
              <td>{_status_badge(bool(r.get("compliant")))}</td>
              <td style="max-width:400px;white-space:pre-wrap">{html.escape(r.get("details",""))}</td>
            </tr>"""

        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        page = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AEGIS Compliance Report — {html.escape(instance_name or instance_id)}</title>
  <style>
    body {{font-family:Arial,sans-serif;margin:24px;background:#f4f6f8}}
    h1 {{color:#2c3e50}}
    .summary-box {{display:flex;gap:24px;margin:16px 0}}
    .stat {{background:#fff;border-radius:8px;padding:16px 24px;text-align:center;box-shadow:0 2px 4px rgba(0,0,0,.1)}}
    .stat .num {{font-size:2em;font-weight:bold;color:{color}}}
    table {{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 2px 4px rgba(0,0,0,.1)}}
    th {{background:#2c3e50;color:#fff;padding:10px 8px;text-align:left}}
    td {{padding:8px;border-bottom:1px solid #ecf0f1;vertical-align:top}}
    tr:hover {{background:#f8f9fa}}
    .footer {{color:#7f8c8d;margin-top:16px;font-size:.85em}}
  </style>
</head>
<body>
  <h1>AEGIS Security Hardening — Compliance Report</h1>
  <p><strong>Instance:</strong> {html.escape(instance_name or instance_id)}<br>
     <strong>Job ID:</strong> {html.escape(job_id)}<br>
     <strong>Generated:</strong> {generated_at}</p>
  <div class="summary-box">
    <div class="stat"><div class="num">{total}</div>Total Rules</div>
    <div class="stat"><div class="num" style="color:#27ae60">{pass_count}</div>Pass</div>
    <div class="stat"><div class="num" style="color:#c0392b">{fail_count}</div>Fail</div>
    <div class="stat"><div class="num" style="color:{color}">{pass_pct}%</div>Compliance Score</div>
  </div>
  <table>
    <thead><tr>
      <th>Rule ID</th><th>Title</th><th>Severity</th><th>Component</th><th>Status</th><th>Details</th>
    </tr></thead>
    <tbody>{rows}</tbody>
  </table>
  <p class="footer">Generated by Project AEGIS &mdash; HPE Private Cloud Security Hardening</p>
</body>
</html>"""

        filename = f"report_{job_id}_{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}.html"
        file_path = self.reports_dir / filename
        file_path.write_text(page, encoding="utf-8")
        return str(file_path)
